### PR TITLE
allow chaining of plugins and extends

### LINKED ISSUE #321: support plugins extending other plugins
The main use case is to have a plugin extend base `recommended` so you don't have to do `extends: ['recommended', 'plugin1:recommended'],` yourself. I tried inside of a plugin:

```js
configurations: {
  recommended: {
    extends: 'recommended',
    rules: {
    }
  }
}
```

but it didn't work.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #321

### CODE REVIEW

**Comment by kellyselden** [comment]
Blocked by #323 (the reason for the test failures).

**Comment by kellyselden** [comment]
now working and no longer affected by the mutated config.

**Comment by rwjblue** [comment]
Will need a rebase...

**Comment by kellyselden** [comment]
> Can you add a test that shows what happens to a circular reference?

What would you like to happen? Throw if another plugin with the same name is found?

**Comment by rwjblue** [comment]
Well, it isn't 100% obvious what should happen.  I think we have (at least) the following options:

* Throw if we hit some amount of recursion
* Attempt to process a certain number of loops

I _think_ the safe bet is to throw if we detect recursion for now, that way if we figure out a real solution we can remove the error without a breaking change...

What do you think?

**Comment by kellyselden** [comment]
I went Above and Beyond™ and added loop detection code. Let me know what you think.

**Comment by kellyselden** [comment]
The Travis gods are now pleased.

**Comment by kellyselden** [comment]
@rwjblue ping

**Pull request merged**
