### PR TITLE
invalid-interactive: allow form elements to have onsubmit attributes

### PR DESCRIPTION
**Pull request by bendemboski**
The rule allows `<form {{action "foo" on="submit"}}>` but not `<form onsubmit={{action "foo"}}>`. Now it allows both.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like I just created a merge conflict for you here, would you mind updating?

**Comment by bendemboski** [comment]
rebased

**Comment by rwjblue** [comment]
I just resolved the conflict I created, will land once CI is green...

**Comment by rwjblue** [comment]
Thanks @bendemboski, very sorry I let this sit so long

**Comment by bendemboski** [comment]
No problem -- glad to help the continued improvement of this excellent addon 😃

**Pull request merged**
