### PR TITLE
Add inline-link-to rule

### PR DESCRIPTION
**Pull request by mitchlloyd**
I wanted to get my feet wet with this project and I don't like the inline form of link to so I took a shot at implementing a rule for #60.

Let me know what you think!

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks great! @nathanhammond and I share your hatred of inline link-to...

My only question is RE: the rule name.  I realize that they are all over the map so far and I should come up with a "rule for the rule names". 

Would this rule may be better as `inline-link-to` (which follows the patter of `triple-curlies` / `bare-strings` / `nested-interactive` / `self-closing-void-elements` and forbids the thing it describes)?

**Comment by mitchlloyd** [comment]
"inline-link-to" works for me. Going forward maybe this project could adopt
naming similar to ESLint where rules are generally affirmative "eqeqeq" and
forbidding rules begin with "no".

**Comment by rwjblue** [comment]
Yeah, I agree

**Comment by mitchlloyd** [comment]
Updated. Seems like a good one to squash if this looks good.

**Pull request merged**
