### PR TITLE
Add require option for self-closing-void-elements

### PR DESCRIPTION
**Pull request by akashdsouza**
#121

### CODE REVIEW

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by rwjblue** [comment]
Can you also add details to the README for this configuration?

**Comment by akashdsouza** [comment]
Sure

**Comment by rwjblue** [comment]
FYI - a recent PR landed that moves things into docs/rules/**.md files (and link to them from the README), so you'll need to update that file instead of the README.

**Comment by akashdsouza** [comment]
I have updated the README although I'm not sure if this is the correct way to specify the configuration details

**Comment by rwjblue** [comment]
Thank you!!

**Pull request merged**
