### PR TITLE
Replace "glimmer-engine" with "@glimmer/syntax" and "@glimmer/compiler"

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like `power-assert` is doing some strange stuff... I'm working on replacing it with Chai instead

**Comment by rwjblue** [comment]
hehe, `power-assert` was a fun experiment, but its definitely finnicky...

**Comment by Turbo87** [comment]
yeah, I'm used to this style of assertions from https://docs.pytest.org/ but it certainly has its downsides...

**Comment by Turbo87** [comment]
looks like we have two options here:

- v0.21.x and v0.22.x of the `@glimmer` packages are not compatible with Node 4 because the use destructuring

- v0.23.0-beta is apparently breaking a lot of tests here 😞

**Comment by rwjblue** [comment]
We can fix 0.22 and publish an update

**Comment by Turbo87** [comment]
> We can fix 0.22 and publish an update

It looks like we would need to touch `emberjs-build` for that. I've tried to build `glimmer-vm@0.22.0` but it just failed and I have no idea how to make it work since it seems to throw several issues somewhere in lerna... I give up

**Comment by Turbo87** [comment]
I've had another look at this and it seems that `node.loc.start` is often wrong which seems to be causing most of the test failures...

**Comment by rwjblue** [comment]
😭

**Comment by rwjblue** [comment]
Just rebased and fixed things up.  Waiting for CI to agree, but will land once finished.

**Comment by Turbo87** [comment]
🎉  thanks!

**Pull request merged**
