### PR TITLE
Added table-groups rule

### LINKED ISSUE #280: Require tables to be properly formed HTML.
Require `<thead>` and/or `<tbody>`.  This avoids a very nuanced (and possibly deprecated in the future) feature of glimmer that auto-inserts these tags.

Bad:

```hbs
<table>
  <tr>
    <td></td>
  </tr>
</table>
```

```hbs
<table>
  {{#each foo as |item|}}
    {{some-thing-that-has-tagName-tr item=item}}
  {{/each}}
</table>
```

```hbs
<table>
  {{some-thing item=item}}
</table>
```

Good:

```hbs
<table>
  <tbody>
    <tr>
      <td></td>
    </tr>
  </tbody>
</table>
```

```hbs
<table>
  <tbody>
    {{#each foo as |item|}}
      {{some-thing-that-has-tagName-tr item=item}}
    {{/each}}
  </tbody>
</table>
```

```hbs
<table>
  <tbody>
    {{some-thing-that-has-tagName-tr}}
  </tbody>
</table>
```

### PR DESCRIPTION
**Pull request by t-sauer**
Closes #280 

I assume, that the same applies for `tfoot`.

### CODE REVIEW

**Comment by rwjblue** [comment]
Yes, absolutely. I just forgot about `tfoot `...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by t-sauer** [comment]
Empty tables were actually reported as invalid. Should be good now.

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
Published in 0.8.8.

**Pull request merged**
