### PR TITLE
Don't allow trailing dots in a PathExpression

### PR DESCRIPTION
**Pull request by siva-sundar**
Implements https://github.com/rwjblue/ember-template-lint/issues/341

### CODE REVIEW

**Comment by siva-sundar** [comment]
I have added more info about the rule. Please let me know if anything else is required.

**Comment by siva-sundar** [comment]
@rwjblue is there anything that needs to be updated in this PR?

**Comment by siva-sundar** [comment]
I have 2 opinions:

1) This leads to another issue too, consider the following code
```js
<div class={{if some.path. 'a'}}>Sample Text</div>
```
Where some.path is a controller property, this renders as follows
```js
<div class="<twiddle@controller:application::ember232>">Sample Text</div>
```


2) Can we have this until this error is thrown from Glimmer?

**Comment by siva-sundar** [comment]
Hey @rwjblue any updates?

**Comment by Turbo87** [comment]
@rwjblue @siva-sundar it looks like this PR is restricting us from updating to the latest `@glimmer/compiler` release. with that release the parser will fail and no longer be able to parse the template at all. the only option I see is removing the rule again 🤔

**Pull request merged**
